[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    hideakitai/MPU9250
    https://github.com/T-vK/ESP32-BLE-Mouse

build_flags =
    -D CONFIG_ESP_COREDUMP_ENABLE=0